language: go

services:
  - docker

os:
- linux

go:
- "1.14"

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"


script:
  - fossa init
  - fossa analyze
  - make docker-build

after_success:
  - fossa test

deploy:
  provider: script
  script: make docker-push
  on:
    branch: master